### ISSUE TITLE
Nothing happens when inserting symbol

### ISSUE THREAD

**Issue by david-hakansson** [fsmMLK/inkscapeCircuitSymbols#10]
Hi,
On Windows 10 Pro, 64-bit system. Tried to install Inkscape 0.92.4, 32 bit version to use the CircuitSymbols. When trying to insert any symbol in InkScape I see a window flashing by really quickly and then disappears. If I press the Apply button repeatedly I'm able to read the text: 'General' working, please wait.

But nothing happens. No symbol is inserted. I have tried with and without LaTex, doesn't make any difference.

Am I doing something wrong?

Best regards.
David

**Comment by fsmMLK** [comment]
no idea. I installed it a couple of times on differente Windows machines and they worked fine (no latex)

**Comment by gijsbent** [comment]
I experience the same issue, is this problem already solved?
