### ISSUE TITLE
Error on inserting symbol: Command pdflatex /tmp/tmppO1tu4/tmp.tex -interaction=nonstopmode -halt-on-error failed: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by TheBeneficent** [fsmMLK/inkscapeCircuitSymbols#12]
![Screenshot from 2019-12-02 00-50-25](https://user-images.githubusercontent.com/38909352/69920485-de497b00-149d-11ea-923f-b22dc777a459.png)

**Comment by fsmMLK** [comment]
which pdf to svg are you using?
