### ISSUE TITLE
BJT arrow disappear

### ISSUE THREAD

**Issue by its-fonsy** [fsmMLK/inkscapeCircuitSymbols#14]
When I have to draw two BJT, after clicking 'Apply' to draw the 2nd one, the arrow on the first one disappear.

**Comment by fsmMLK** [comment]
can you attach one svg file with the two BJTs?

**Comment by its-fonsy** [comment]
The file is there [ink-bug.tar.gz](https://github.com/fsmMLK/inkscapeCircuitSymbols/files/4058235/ink-bug.tar.gz).
I have also recorded a short GIF to show you what I am doing.
![inkscape-bug](https://user-images.githubusercontent.com/52673811/72329577-48685900-36b5-11ea-9fa6-86771b187ea9.gif)
As you can see when I create the 2nd npn, the first one lose the arrow of the emitter.

**Comment by fsmMLK** [comment]
The file you sent me opens fine here on my machine.
Try to restart inkscape and open the file you sent me. See if the arrows appear.

It might be an issue with your inkscape. Which version are you using?

**Comment by its-fonsy** [comment]
I am using `Inkscape 0.92.4`, but even with the `0.91` I had the same issue.
I've tried to export the image in `.png` and `.svg` format and both BJTs has arrows. I didn't do it before because I was assuming that Inkscape would have exported what I was seeing.
