### ISSUE TITLE
Doesn't work: Problem with 'parseColorPicker'

### ISSUE THREAD

**Issue by soerenhm** [fsmMLK/inkscapeCircuitSymbols#25]
Hi, thanks for this extension.

I just installed it on Inkscape 1.0.2-2 but get the following error whenever I try to insert a circuit symbol:

Traceback (most recent call last):
  File "circuitSymbols.py", line 567, in <module>
    circuit.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 140, in run
    self.save_raw(self.effect())
  File "circuitSymbols.py", line 231, in effect
    [self.voltageColor, alpha] = inkDraw.color.parseColorPicker(so.voltColor, so.colorPickerVolt)
ValueError: too many values to unpack (expected 2)

I guess it's really a problem with the inkDraw package?

**Comment by fsmMLK** [comment]
fixed the bug. Check the newest version

**Comment by soerenhm** [comment]
Yep, it works now - thanks!
