### ISSUE TITLE
Extension greyed out

### ISSUE THREAD

**Issue by rahna803** [fsmMLK/inkscapeCircuitSymbols#29]
Hi,
I wanted to use your library for my thesis work, I installed all the plugins and extensions, but the option is greyed out as shown.
![image](https://user-images.githubusercontent.com/76702936/133878640-45f30742-c91a-42b1-9c23-7a1e76864078.png)
any suggestions?

**Comment by fsmMLK** [comment]
try opening inkscape from the terminal and look for the output. It might show what the problem might be. Usually it means inkscape cannot find all necessary files to open it. 

which inkscape version are you using?

**Comment by rahna803** [comment]
> try opening inkscape from the terminal and look for the output. It might show what the problem might be. Usually it means inkscape cannot find all necessary files to open it.
> 
> which inkscape version are you using?

The error message is get is:

** (org.inkscape.Inkscape:3736): WARNING **: 14:17:36.636: Failed to find resource file 'inkscapeMadeEasy/inkscapeMadeEasy_Base.py'. Looked in:
        C:\Users\ran\AppData\Roaming\inkscape\extensions\inkscapeMadeEasy/inkscapeMadeEasy_Base.py
        C:\Program Files\Inkscape\share\inkscape\extensions\inkscapeMadeEasy/inkscapeMadeEasy_Base.py

** (org.inkscape.Inkscape:3736): WARNING **: 14:17:36.659: Failed to find resource file 'inkscapeMadeEasy/inkscapeMadeEasy_Draw.py'. Looked in:
        C:\Users\ran\AppData\Roaming\inkscape\extensions\inkscapeMadeEasy/inkscapeMadeEasy_Draw.py
        C:\Program Files\Inkscape\share\inkscape\extensions\inkscapeMadeEasy/inkscapeMadeEasy_Draw.py

** (org.inkscape.Inkscape:3736): WARNING **: 14:17:36.674: Failed to find resource file 'inkscapeMadeEasy/inkscapeMadeEasy_Base.py'. Looked in:
        C:\Users\ran\AppData\Roaming\inkscape\extensions\inkscapeMadeEasy/inkscapeMadeEasy_Base.py
        C:\Program Files\Inkscape\share\inkscape\extensions\inkscapeMadeEasy/inkscapeMadeEasy_Base.py

** (org.inkscape.Inkscape:3736): WARNING **: 14:17:36.688: Failed to find resource file 'inkscapeMadeEasy/inkscapeMadeEasy_Draw.py'. Looked in:
        C:\Users\ran\AppData\Roaming\inkscape\extensions\inkscapeMadeEasy/inkscapeMadeEasy_Draw.py
        C:\Program Files\Inkscape\share\inkscape\extensions\inkscapeMadeEasy/inkscapeMadeEasy_Draw.py


The inkscape version in 1.0

**Comment by rahna803** [comment]
well i did end up resolving that issue, now i have a newer issuee:
    import textextLib.textext as textext
ModuleNotFoundError: No module named 'textextLib'

**Comment by fsmMLK** [comment]
you have to install the version on 'latest' folder.

**Comment by rahna803** [comment]
Installed everything all over again, the extensions work, but they are a bit slow.
