### ISSUE TITLE
Problem for a new user

### ISSUE THREAD

**Issue by Niinaaaaa** [fsmMLK/inkscapeCircuitSymbols#32]
Hi!

I have downloaded Inkscape, inkscapeMadeEasy and CircuitSymbols. I think I followed every step. At this point, I didn't download Latex so I did remove that one # as it was told.

Now I have tried to use CircuitSymbols at Inkscape, but I get this error message, when I click use/apply-button.

Have I done something wrong or is this a bug? Thank you!

Traceback (most recent call last):
  File "C:\Users\Käyttäjä\AppData\Roaming\inkscape\extensions\circuitSymbols\circuitSymbols.py", line 645, in <module>
    circuit = CircuitSymbols()
  File "C:\Users\Käyttäjä\AppData\Roaming\inkscape\extensions\circuitSymbols\circuitSymbols.py", line 60, in __init__
    self.arg_parser.add_argument("--bipoleRLCvariable", type=self.bool, dest="bipoleRLCvariable", default=False)
AttributeError: 'CircuitSymbols' object has no attribute 'bool'

**Comment by fsmMLK** [comment]
I think you have problems installing inkscapeMadeEasy. the definition of Bool is there. Please check your installation.

Which version of inkscape are you using? which versions of inkscapeMadeEasy and CircuitSymbols are you using?
