### ISSUE TITLE
Can't have a component without value

### ISSUE THREAD

**Issue by josejsarmento** [fsmMLK/inkscapeCircuitSymbols#34]
OS: Mac OS 12.6
Inkscape version: 1.2.1
inkscapeCircuitSymbols version: [05b434f](https://github.com/fsmMLK/inkscapeCircuitSymbols/commit/05b434fc3f2a1783433662967d24213bdd78a73c)

Hello, I'm trying to place a component without a value, but it keeps automatically adding one. In my case, I want to place a resistor with no value, but it adds a 'Z' by default.

[Here are the screenshots](https://imgur.com/a/Btgz1z0).

**Comment by fsmMLK** [comment]
I will move this to 'feature requests'.

**Comment by fsmMLK** [comment]
done!
