### ISSUE TITLE
Works great on ubuntu 16.04, minor comments

### ISSUE THREAD

**Issue by calocedrus** [fsmMLK/inkscapeCircuitSymbols#6]
Smooth installation on ubuntu 16.04 with tex live, inkscape 0.91, an impressive work and package!
Small remarks:

- For inkscapeMadeEasy, I had to install steinmetz.sty which was missing, I did it with `sudo apt install texlive-science` (ref. this [tex.stackexchange](https://tex.stackexchange.com/a/439029/122024))

- For inkscapeCircuitSymbols, in your Installation and requirements directory structure, you forgot to mention circuitSymbols_general.inx, which makes that only the semiconductor menu entry appears.

- you could mention in your readme that the menu entries are found under **extensions > fsmMLK > Circuit symbols**.

Cheers!

**Comment by fsmMLK** [comment]
Thanks, these comments were added. They will be uploaded shortly.
