### ISSUE TITLE
european and ameriсan style

### ISSUE THREAD

**Issue by greengrocer98** [fsmMLK/inkscapeCircuitSymbols#7]
It would be nice to add european and american style to bipoles. Design is very similar to circuitikz. It also would be nice to add circuitikz export. I have been searching for circuitikz gui for 2 weeks and eventually found.

**Comment by fsmMLK** [comment]
added IEEE/ IEC stardards to RLC bipoles and sources.

circuiTikz export is very unlikely to happen. =S
